version: '3.8'
services:
  postgres:
    image: postgres:13.2
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prismapoc-local

  proofofconcept:
    build:
      context: ./
      target: prismapoc
    volumes: 
      - ./:/usr/src/app
    environment:
      - PORT=${PORT:-4000}
      - POSTGRES_URL=${POSTGRES_URL}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - NODE_ENV=${NODE_ENV:-local}
    ports: 
      - ${PORT:-4000}:${PORT:-4000}
    networks:
      - prismapoc-local
    # command: /bin/bash -c "npm i && npm run db:migrate && npm run db:seed:all && npm run dev"
    command: /bin/bash -c "npm i && npm run dev"
    depends_on:
      postgres:
        condition: service_healthy
  
networks:
  prismapoc-local:
    driver: bridge